# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'FunCorpTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FunCorpTest
  pod 'Realm', '3.13.1'
  pod 'AFNetworking','3.2.1'
  pod 'MD5Digest', '1.1.0'
  pod 'CHTCollectionViewWaterfallLayout', '0.9.7'

end
